services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006      # Web viewer
      - 3389:3389/tcp  # RDP
      - 3389:3389/udp
    volumes:
      - $HOME/Windows:/storage
      - $HOME/WinShared:/shared   # host <-> VM file exchange ("Shared" on Win desktop)
    stop_grace_period: 2m
