-- Auto-generated by theme-switch. Do not edit.
-- Source of truth: ~/.config/palette/active.json

local hex = {
  base = "1e1e2e",
  blue = "89b4fa",
  crust = "11111b",
  flamingo = "f2cdcd",
  green = "a6e3a1",
  lavender = "b4befe",
  mantle = "181825",
  maroon = "eba0ac",
  mauve = "cba6f7",
  overlay0 = "6c7086",
  overlay1 = "7f849c",
  overlay2 = "9399b2",
  peach = "fab387",
  pink = "f5c2e7",
  red = "f38ba8",
  rosewater = "f5e0dc",
  sapphire = "74c7ec",
  sky = "89dceb",
  subtext0 = "a6adc8",
  subtext1 = "bac2de",
  surface0 = "313244",
  surface1 = "45475a",
  surface2 = "585b70",
  teal = "94e2d5",
  text = "cdd6f4",
  yellow = "f9e2af",
}

local function alpha(o)
  return string.format("%02x", math.floor((o or 1.0) * 255))
end

local p = {}
for name, h in pairs(hex) do
  p[name] = h
  p[name .. "_rgb"]  = function()  return "rgb("  .. h .. ")" end
  p[name .. "_rgba"] = function(o) return "rgba(" .. h .. alpha(o) .. ")" end
end
return p
