-- Auto-generated by theme-switch. Do not edit.
-- Source of truth: ~/.config/palette/active.json

local hex = {
  base = "eff1f5",
  blue = "1e66f5",
  crust = "dce0e8",
  flamingo = "dd7878",
  green = "40a02b",
  lavender = "7287fd",
  mantle = "e6e9ef",
  maroon = "e64553",
  mauve = "8839ef",
  overlay0 = "9ca0b0",
  overlay1 = "8c8fa1",
  overlay2 = "7c7f93",
  peach = "fe640b",
  pink = "ea76cb",
  red = "d20f39",
  rosewater = "dc8a78",
  sapphire = "209fb5",
  sky = "04a5e5",
  subtext0 = "6c6f85",
  subtext1 = "5c5f77",
  surface0 = "ccd0da",
  surface1 = "bcc0cc",
  surface2 = "acb0be",
  teal = "179299",
  text = "4c4f69",
  yellow = "df8e1d",
}

local function alpha(o)
  return string.format("%02x", math.floor((o or 1.0) * 255))
end

local p = {}
for name, h in pairs(hex) do
  p[name] = h
  p[name .. "_rgb"]  = function()  return "rgb("  .. h .. ")" end
  p[name .. "_rgba"] = function(o) return "rgba(" .. h .. alpha(o) .. ")" end
end
return p
