● /* Window */
window.auth-window.background,
window.auth-window {
    background-color: {< crust >};
}

/* Typography */
.auth-header {
    color: {< text >};
    font-weight: bold;
}

.auth-message {
    color: {< text >};
}

.auth-retry {
    color: {< text >};
}

/* Identity dropdown */
dropdown.auth-identity > button.toggle {
    background: none;
    background-color: {< mantle >};
    border-color: {< surface1 >};
    border-radius: 8px;
    color: {< text >};
}

dropdown.auth-identity > popover.menu > contents,
dropdown.auth-identity listview {
    background-color: {< mantle >};
    border-color: {< surface1 >};
}

dropdown.auth-identity listview > row:hover,
dropdown.auth-identity listview > row:selected {
    background-color: {< base >};
}

dropdown.auth-identity listview > row:focus:not(:hover) {
    background-color: transparent;
}

/* Password entry */
.auth-password {
    background: {< mantle >};
    border-color: {< surface1 >};
    border-radius: 8px;
    color: {< text >};
}

entry.auth-password:focus-within {
    outline-color: {< surface0 >};
}

/* Buttons */
.auth-buttons {
    margin-top: 4px;
}

.auth-cancel,
.auth-confirm {
    background: {< mantle >};
    border-color: {< surface1 >};
    color: {< text >};
}

.auth-cancel:hover,
.auth-confirm:hover {
    background: {< base >};
}
